# Numpy examples

In [ ]:
!pip install numpy

**Comparison between numpy and python lists**

In [1]:
import numpy as np
import time

# Using lists
list1 = list(range(1000000))
list2 = list(range(1000000))
start = time.time()
result = [x + y for x, y in zip(list1, list2)]
print("List addition time:", time.time() - start)

# Using NumPy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)
start = time.time()
result = array1 + array2
print("NumPy addition time:", time.time() - start)


List addition time: 0.0849149227142334
NumPy addition time: 0.02525806427001953


**Comparison of summing elements in Python lists vs. NumPy arrays**

In [2]:
import numpy as np

# Sum of elements in a Python list
python_list = [1, 2, 3, 4]
python_list_sum = [x + 2 for x in python_list]

# Sum of elements in a NumPy array
numpy_array = np.array([1, 2, 3, 4])
numpy_array_sum = numpy_array + 2

print("Python list sum:", python_list_sum)
print("NumPy array sum:", numpy_array_sum)


Python list sum: [3, 4, 5, 6]
NumPy array sum: [3 4 5 6]


**Array creation**

In [5]:
# Creating different types of arrays
array_from_list = np.array([1, 2, 3, 4])
array_zeros = np.zeros((2, 3))  # 2x3 array of zeros
array_ones = np.ones((3, 3))    # 3x3 array of ones
array_range = np.arange(0, 10, 2)  # Values from 0 to 10, step 2
array_linspace = np.linspace(0, 1, 5)  # 5 equally spaced values from 0 to 1

print("Array from list:", array_from_list)
print("Zeros array:", array_zeros)
print("Ones array:", array_ones)
print("Range array:", array_range)
print("Linspace array:", array_linspace)


Array from list: [1 2 3 4]
Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


**Basic operations and functions**

Vectorized Arithmetic Operations

In [6]:
# Vectorized operations
array = np.array([1, 2, 3, 4])
print("Array + 10:", array + 10)
print("Array * 2:", array * 2)

# Statistical functions
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Standard deviation:", np.std(array))
print("Max value:", np.max(array))
print("Min value:", np.min(array))


Array + 10: [11 12 13 14]
Array * 2: [2 4 6 8]
Sum: 10
Mean: 2.5
Standard deviation: 1.118033988749895
Max value: 4
Min value: 1


**Broadcasting**

In [7]:
# Broadcasting example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])

result = matrix + vector  # Broadcasting
print("Result of broadcasting:", result)


Result of broadcasting: [[2 4 6]
 [5 7 9]]


**Array Manipulation**

In [8]:
# Indexing and slicing
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at (0, 1):", array[0, 1])  # First row, second column
print("First row:", array[0, :])          # First row
print("Second column:", array[:, 1])      # Second column

# Reshaping array
reshaped_array = array.reshape(1, 9)
print("Reshaped array:", reshaped_array)

# Concatenating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated = np.concatenate((array1, array2))
print("Concatenated array:", concatenated)


Element at (0, 1): 2
First row: [1 2 3]
Second column: [2 5 8]
Reshaped array: [[1 2 3 4 5 6 7 8 9]]
Concatenated array: [1 2 3 4 5 6]
