**Exercise 1:** Create an array of 20 simulated temperature values and perform the following operations: 
* Calculate the mean, standard deviation, minimum, and maximum. 
* Add 2 degrees to each temperature value. 
* Reshape the array to a 4x5 matrix.


In [1]:
import numpy as np

# Create temperature array
temperatures = np.array([23, 25, 21, 19, 20, 22, 24, 23, 19, 18, 17, 22, 23, 21, 20, 22, 24, 23, 25, 21])

# Statistical calculations
print("Mean temperature:", np.mean(temperatures))
print("Standard deviation:", np.std(temperatures))
print("Minimum temperature:", np.min(temperatures))
print("Maximum temperature:", np.max(temperatures))

# Add 2 degrees to each temperature value
temperatures += 2
print("Temperatures after adding 2 degrees:", temperatures)

# Reshape to 4x5
reshaped_temperatures = temperatures.reshape(4, 5)
print("Reshaped temperatures:", reshaped_temperatures)



Mean temperature: 21.6
Standard deviation: 2.2
Minimum temperature: 17
Maximum temperature: 25
Temperatures after adding 2 degrees: [25 27 23 21 22 24 26 25 21 20 19 24 25 23 22 24 26 25 27 23]
Reshaped temperatures: [[25 27 23 21 22]
 [24 26 25 21 20]
 [19 24 25 23 22]
 [24 26 25 27 23]]


**Exercise 2:** Given a quarterly sales array for two products, calculate the annual total and the quarterly average.

In [2]:
import numpy as np

# Quarterly sales data for two products over four quarters
product_A_sales = np.array([1500, 2000, 2500, 3000])  # Sales for Product A
product_B_sales = np.array([1200, 1800, 2200, 2400])  # Sales for Product B

# Calculate the annual total sales for each product
annual_total_A = np.sum(product_A_sales)
annual_total_B = np.sum(product_B_sales)

# Calculate the quarterly average sales for each product
quarterly_avg_A = np.mean(product_A_sales)
quarterly_avg_B = np.mean(product_B_sales)

# Print results
print("Annual total sales for Product A:", annual_total_A)
print("Annual total sales for Product B:", annual_total_B)
print("Quarterly average sales for Product A:", quarterly_avg_A)
print("Quarterly average sales for Product B:", quarterly_avg_B)


Annual total sales for Product A: 9000
Annual total sales for Product B: 7600
Quarterly average sales for Product A: 2250.0
Quarterly average sales for Product B: 1900.0


**Exercise 3:** Use np.where to create a mask identifying values above the mean in the temperature array.

In [3]:
import numpy as np

# Create the temperature array
temperatures = np.array([23, 25, 21, 19, 20, 22, 24, 23, 19, 18, 
                         17, 22, 23, 21, 20, 22, 24, 23, 25, 21])

# Calculate the mean temperature
mean_temperature = np.mean(temperatures)
print("Mean temperature:", mean_temperature)

# Use np.where to create a mask for values above the mean
above_mean_mask = np.where(temperatures > mean_temperature, True, False)

# Print the mask and the corresponding values
print("Mask of temperatures above the mean:", above_mean_mask)
print("Temperatures above the mean:", temperatures[above_mean_mask])


Mean temperature: 21.6
Mask of temperatures above the mean: [ True  True False False False  True  True  True False False False  True
  True False False  True  True  True  True False]
Temperatures above the mean: [23 25 22 24 23 22 23 22 24 23 25]
